### ISSUE TITLE
HackerNews is down

### ISSUE THREAD

**Issue by NoamGoren1** [hkandala/keep-up#9]
Hi Harish Kandala,
Great product
I've notice that the hackernews feed is down
<img width="597" alt="Screenshot 2021-10-21 at 15 49 08" src="https://user-images.githubusercontent.com/80257802/138302616-68a2057c-3d00-4959-86b9-f1ec7e03ff96.png">
wn

**Comment by hkandala** [comment]
Hackernews has updated class name of links causing the failure.
Resolved the issue, hackernews feed is up now.
Thanks for reporting!
